In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
from sklearn.datasets import load_diabetes

In [4]:
X, y = load_diabetes(return_X_y=True)

In [54]:
print(X.shape, y.shape)

(442, 10) (442,)


In [55]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [56]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [58]:
lr = LinearRegression()

In [59]:
lr.fit(X_train, y_train)

LinearRegression()

In [60]:
y_pred = lr.predict(X_test)

In [61]:
r2_score(y_test, y_pred)

0.5188113124539249

In [62]:
lr.coef_

array([  23.45465406, -247.42747406,  492.1087518 ,  329.35876431,
       -970.79723039,  573.54295519,  182.42162368,  255.92168168,
        794.21609282,   89.32249214])

In [63]:
lr.intercept_

np.float64(152.13623331746496)

In [64]:
X_train.shape

(353, 10)

In [79]:
class BatchGDRegressor:

  def __init__(self, learning_rate=0.01, epochs=100):
    self.coef_ = None
    self.intercept_ = None
    self.lr = learning_rate
    self.epochs = epochs


  def fit(self, X_train, y_train):
    # initialize your coef
    self.intercept_ = 0
    self.coef_ = np.ones(X_train.shape[1])

    for i in range (self.epochs):
      # update all the coef and the intercept
      y_hat = np.dot(X_train, self.coef_) + self.intercept_
      intercept_der = -2 * np.mean(y_train - y_hat)
      # print("Shape of y_hat:", y_hat.shape)
      self.intercept_ = self.intercept_ - (self.lr * intercept_der)

      coef_der = -2 * np.dot((y_train - y_hat), X_train)/X_train.shape[0]
      self.coef_ = self.coef_ - (self.lr * coef_der)

    print(self.intercept_, self.coef_)


  def predict(self, X_test):
    return np.dot(X_test, self.coef_) + self.intercept_

In [127]:
bgdr = BatchGDRegressor(learning_rate=0.5, epochs=1000)

In [128]:
bgdr.fit(X_train, y_train)

152.06801967664444 [  31.71570101 -199.21105871  477.36734985  310.97539649  -59.49851929
 -119.93354137 -210.22765043  140.69112514  408.33817465  135.06859109]
