#DAY 6


#**NUMPY**

##FOUNDATIONAL NUMPY

Behind the scene C++ is working. But Python uses api for using numpy an d intereaction between user and computer

In [2]:
import numpy as np
import time

In [3]:
arr_1d = np.array([1,2,3,4,5,6])
print("1D array :", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array :", arr_2d)

1D array : [1 2 3 4 5 6]
2D array : [[1 2 3]
 [4 5 6]]


###List Vs Numpy


In [4]:
py_list = [1,2,3,4]
print("list multiplication :", py_list * 2) #list get multiplied and return each value n times

np_arr = np.array([1,2,3,4])
print("array multiplication :", np_arr * 2) #element wise multiple

list multiplication : [1, 2, 3, 4, 1, 2, 3, 4]
array multiplication : [2 4 6 8]


#Efficiency b/w python list and numpy array

In [5]:
start = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List operation time :", time.time() - start)

start = time.time()
np_arr = np.arange(100000) * 2
print("\n Numpy Array operation time :", time.time() - start)


 List operation time : 0.07219743728637695

 Numpy Array operation time : 0.003490924835205078


### Creating from scratch

In [6]:
zeroes = np.zeros((2,3))
print("\n Zeroes Array : \n", zeroes)

ones = np.ones((2,2))
print("\n ones Array : \n", ones)

full = np.full((2,2), 4)
print("\n full Array : \n", full)

random = np.random.random((2,3)) # RANDOM VALUES WILL BE FLUCTUATING B/W 0 AND 1
print("\n random array :", random)

sequence = np.arange(0,20,2)
print("\n sequence array :", sequence)


 Zeroes Array : 
 [[0. 0. 0.]
 [0. 0. 0.]]

 ones Array : 
 [[1. 1.]
 [1. 1.]]

 full Array : 
 [[4 4]
 [4 4]]

 random array : [[0.89125778 0.50303662 0.58935913]
 [0.5716422  0.02011132 0.21281754]]

 sequence array : [ 0  2  4  6  8 10 12 14 16 18]


#Vector, Matrix and Tensor

In [7]:
vector = np.array([1,2,3,4,5])    #1D
print("\n vector :", vector)

matrix = np.array([[1,2,3,4],       #2D
                   [5,6,7,8]])
print("\n matrix :", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])    #  >2D -> multi-dimensions
print("\n tensor :", tensor)


 vector : [1 2 3 4 5]

 matrix : [[1 2 3 4]
 [5 6 7 8]]

 tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##Array Properties

In [8]:
arr = np.array([[1,2,3],
                 [4,5,6]])
print("Shape :", arr.shape)         # return the shape of the matrix or vector or tensor whatever you can say (n X m)
print("Dimension :", arr.ndim)      # return the dimension of the array
print("Size :", arr.size)           # return total no. of element in the array
print("DataType :", arr.dtype)

Shape : (2, 3)
Dimension : 2
Size : 6
DataType : int64


##Array Reshaping

In [9]:
arr = np.arange(25)
print("\n Original Array :",arr)

reshaped = arr.reshape(5,5)                     # convert the into (n x m) using reshape method
print("\n Reshaped Array :\n",reshaped)

flatten = reshaped.flatten()
print("\n Flatten Array :",flatten)             # convert the reshape array into original array ( return copy of reshaped)

raveled = reshaped.ravel()
print("\n Raveled Array :",raveled)             # return the view (original) instead of copy

#Transpose
transpose = reshaped.T
print("\n Transpose Array :\n",transpose)


 Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

 Reshaped Array :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

 Flatten Array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

 Raveled Array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

 Transpose Array :
 [[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


#DAY 7

##Phase 2

In [12]:
arr = np.arange(21)
print(arr)

#Slicing
print("\nBasic slicning :", arr[2:7])
print("\nWith step slicning :", arr[2:8:2])
print("\nNegatived slicning :", arr[-3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Basic slicning : [2 3 4 5 6]

With step slicning : [2 4 6]

Negatived slicning : 18


In [13]:
#Slicing in 2D array
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element :", arr_2d[0,2])
print("Entire Row :", arr_2d[1])
print("Entire Column :", arr_2d[:, 2])

Specific Element : 3
Entire Row : [4 5 6]
Entire Column : [3 6 9]


##Sorting


In [17]:
unsorted = np.array([2,3,1,65,3,43,6,1,4,2,64,2,5,2,3])
print("Sorted Array :", np.sort(unsorted))

unsorted_2d_arr = np.array([[4,2], [4,1], [2,3]])
print("Sorted 2D array column-wise", np.sort(unsorted_2d_arr, axis=0))
print("Sorted 2D array column-wise", np.sort(unsorted_2d_arr, axis=1))

Sorted Array : [ 1  1  2  2  2  2  3  3  3  4  5  6 43 64 65]
Sorted 2D array column-wise [[2 1]
 [4 2]
 [4 3]]
Sorted 2D array column-wise [[2 4]
 [1 4]
 [2 3]]


##Filter

In [19]:
number = np.arange(21)
even_numbers = number[number % 2 == 0]
print(even_numbers)


odd_numbers = number[number % 2 != 0]
print(odd_numbers)

[ 0  2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]


##Filter By Mask

In [21]:
mask = number > 5
print("Numbers greater than 5 :", number[mask])
mask

Numbers greater than 5 : [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [23]:
where_result = np.where(number > 5)
print("Where :", number[where_result])
print(where_result)

Where : [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),)


In [36]:
num = np.arange(11)
conditional_array = np.where(num > 5, num * 10, num)
print(conditional_array)


conditional_array = np.where(num > 5, "True", "False")
print(conditional_array)

[  0   1   2   3   4   5  60  70  80  90 100]
['False' 'False' 'False' 'False' 'False' 'False' 'True' 'True' 'True'
 'True' 'True']


##Adding and Removing Data